spring:
  datasource:
    url: jdbc:h2:mem:flowstudydb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # 自動根據 Entity 更新資料表結構
    show-sql: true     # 在終端機印出 SQL 語法，方便我們除錯與驗證
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true    # 啟動 H2 網頁版控制台
      path: /h2-console